[workspace]
members = ["lib-common", "lib-wavesabre", "lib-song", "bin-starter"]
resolver = "2"

# 64k binary optimization profile (applies to the whole workspace; the release
# `starter`/`starter.exe` must stay tiny).
[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1

[profile.dev]
panic = "abort"